services:
  zerobyte:
    image: ghcr.io/nicotsx/zerobyte:v0.36
    container_name: zerobyte
    restart: unless-stopped
    environment:
      TZ: UTC
      BASE_URL: ${ZEROBYTE_URL}
      APP_SECRET: ${ZEROBYTE_APP_SECRET}
      LOG_LEVEL: info
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./.volumes/zerobyte/data:/var/lib/zerobyte
      - ./.volumes:/backup-targets:ro
    ports:
      - "127.0.0.1:54096:4096"
    networks:
      - dcu-net

networks:
  dcu-net:
    external: true
