services:
  authentik-postgresql:
    image: postgres:16-alpine
    container_name: authentik-postgresql
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${AUTHENTIK_POSTGRES_DB}
      POSTGRES_USER: ${AUTHENTIK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTHENTIK_POSTGRES_PASSWORD}
    volumes:
      - ./.volumes/authentik/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - dcu-net

  authentik-server:
    image: ghcr.io/goauthentik/server:2026.2.2
    container_name: authentik-server
    command: server
    restart: unless-stopped
    depends_on:
      authentik-postgresql:
        condition: service_healthy
    environment:
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
      AUTHENTIK_POSTGRESQL__NAME: ${AUTHENTIK_POSTGRES_DB}
      AUTHENTIK_POSTGRESQL__USER: ${AUTHENTIK_POSTGRES_USER}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${AUTHENTIK_POSTGRES_PASSWORD}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
      AUTHENTIK_ERROR_REPORTING__ENABLED: "false"
      AUTHENTIK_DISABLE_STARTUP_ANALYTICS: "true"
      AUTHENTIK_DISABLE_UPDATE_CHECK: "true"
      AUTHENTIK_HOST: ${AUTHENTIK_URL}
    volumes:
      - ./.volumes/authentik/data:/data
      - ./.volumes/authentik/custom-templates:/templates
    ports:
      - "127.0.0.1:51000:9000"
    networks:
      - dcu-net

  authentik-worker:
    image: ghcr.io/goauthentik/server:2026.2.2
    container_name: authentik-worker
    command: worker
    restart: unless-stopped
    depends_on:
      authentik-postgresql:
        condition: service_healthy
    environment:
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
      AUTHENTIK_POSTGRESQL__NAME: ${AUTHENTIK_POSTGRES_DB}
      AUTHENTIK_POSTGRESQL__USER: ${AUTHENTIK_POSTGRES_USER}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${AUTHENTIK_POSTGRES_PASSWORD}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
      AUTHENTIK_ERROR_REPORTING__ENABLED: "false"
      AUTHENTIK_DISABLE_STARTUP_ANALYTICS: "true"
      AUTHENTIK_DISABLE_UPDATE_CHECK: "true"
    volumes:
      - ./.volumes/authentik/data:/data
      - ./.volumes/authentik/custom-templates:/templates
    networks:
      - dcu-net

networks:
  dcu-net:
    external: true
